# Generated by Django 5.1.3 on 2024-11-08 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("client_id", models.CharField(max_length=500)),
                ("client_secret", models.CharField(max_length=500)),
                ("title_template", models.CharField(max_length=200)),
                ("description_template", models.TextField()),
                ("tags_template", models.CharField(max_length=500)),
                ("upload_start_time", models.TimeField()),
                ("wait_between_uploads", models.TimeField()),
                ("clips_per_day", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Clip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("tags", models.CharField(max_length=500)),
                ("video", models.FileField(upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="segs.channel"
                    ),
                ),
            ],
        ),
    ]
