# Generated by Django 5.1.3 on 2024-11-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("segs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clip",
            name="was_uploaded",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
