# Generated by Django 5.1.3 on 2024-11-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("segs", "0002_clip_was_uploaded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clip",
            name="was_uploaded",
        ),
        migrations.AddField(
            model_name="clip",
            name="uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
