# Generated by Django 5.1.3 on 2024-11-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("segs", "0003_remove_clip_was_uploaded_clip_uploaded_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="client_id",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="client_secret",
        ),
        migrations.AddField(
            model_name="channel",
            name="auth_json",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
