# Generated by Django 5.1.3 on 2024-11-09 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("segs", "0004_remove_channel_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="upload_end_time",
            field=models.TimeField(default=datetime.time(16, 31, 30, 963105)),
            preserve_default=False,
        ),
    ]
