# Generated by Django 5.1.3 on 2024-11-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("segs", "0005_channel_upload_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="token_json",
            field=models.TextField(blank=True, null=True),
        ),
    ]
