# Generated by Django 5.1.3 on 2024-11-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("segs", "0006_channel_token_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="clip",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
